apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        name: client
    spec:
      containers:
        - name: client
          image: client:1
          imagePullPolicy: IfNotPresent
          ports:
            - name: client
              containerPort: 8080
          volumeMounts:
          - name: client-root
            mountPath: /client
      volumes:
        - name: client-root
          hostPath:
          path: /var/www/kubbe-example/client
