apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: api:1
          imagePullPolicy: IfNotPresent
          ports:
            - name: api
              containerPort: 3000
          command: ["bundle", "exec", "rails", "s", "-p", "3000", "-b", "0.0.0.0"]
          env:
            - name: RAILS_ENV
              value: "production"
            - name: DATABASE_HOST
              value: db-master
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: api
                  key: database_user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api
                  key: database_password
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: api
                  key: secret_key_base
            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: api
                  key: database_port
