apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: example-app
  name: api
  labels:
    app: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      namespace: example-app
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: api:1
          imagePullPolicy: IfNotPresent
          ports:
            - name: api
              containerPort: 3000
          command: ["bundle", "exec", "rails", "s", "-p", "3000", "-b", "0.0.0.0"]
          env:
            - name: RAILS_ENV
              value: "production"
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: api-enviroment
                  key: DATABASE_HOST
            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: api-enviroment
                  key: DATABASE_PORT
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: api-enviroment
                  key: DATABASE_USERNAME
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-enviroment
                  key: DATABASE_PASSWORD
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: api-enviroment
                  key: SECRET_KEY_BASE

