apiVersion: v1
kind: Service
metadata:
  namespace: example-app
  name: api-service
  labels:
    app: api
spec:
  selector:
    app: api
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 3000
