apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: NodePort
#  type: LoadBalancer
  selector:
    name: kube-example
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
