apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-master
  labels:
    app: db-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-master
  template:
    metadata:
      labels:
        app: db-master
    spec:
      containers:
        - name: db-master
          image: mysql:5
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api
                  key: database_password
          ports:
            - containerPort: 3306
              name: db-master
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/mysql
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: nfs-pvc
