apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: example-app
  name: db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  mountOptions:
    - hard
  nfs:
    server: 192.168.99.1
    path: /Users/Shared/Kubernetes/database
