apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: example-app
  name: db-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: slow
